pull_request_rules:
  - name: automatic merge when CI checks pass and at least 2 approved reviews
    conditions:
      - check-success=test
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: squash
