# merge to main actions           
name: Merge to Main

on:
  push:
    branches:
      - workflow   # Change this to your working branch name

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes to main
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff ${{ github.event.ref }}
          git push origin main

